[general]
import = ['~\AppData\Roaming\alacritty\themes\themes\one_dark.toml']

[cursor]
blink_interval = 750

[cursor.style]
blinking = "Always"

[font]
size = 10

[font.normal]
family = "ComicShannsMono Nerd Font Mono"
# family = "FantasqueSansM Nerd Font Mono"
# family = "Cascadia Code NF"
style = "Regular"

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Italic"

[font.offset]
x = 0
y = -1

[font.glyph_offset]
x = 0
y = -1

[scrolling]
history = 99999
multiplier = 3

[terminal.shell]
program = "nu"

[window]
dynamic_title = false
# title = ""
opacity = 0.9999
blur = true

[window.padding]
x = 1
y = 1

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Copy"
key = "Insert"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "Up"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "Down"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Up"
mods = "Shift|Control|Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Down"
mods = "Shift|Control|Alt"
